---
- name: NDB postgres HA template VM setup
  hosts: all
#  remote_user: root
#  become: true

  roles:
    - postgres_ha

  tasks:
    - name: reboot remote server
      reboot:
        reboot_timeout: 300
        msg: "Reboot triggered by Ansible"

    - name: Wait for the remote host to come back online
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        timeout: 300
