---
- name: NDB setup
  hosts: all
#  remote_user: root
#  become: true

  roles:
    - postgres_ha

  tasks:
    - name: Restart server
      command: shutdown -r now "Reboot triggered by Ansible"
      async: 0
      poll: 0
      ignore_errors: true
      notify: Wait for server to restart

  handlers:
    - name: Wait for server to restart
      local_action:
        module: wait_for
          host={{ inventory_hostname }}
          port=22
          delay=1
          timeout=300