---
# "Check system" variables

os_valid_distributions:
  - RedHat
  - CentOS
#  - Rocky
#  - OracleLinux
#  - Ubuntu
#  - Debian
#  - AlmaLinux

os_minimum_versions:
  RedHat: 7
  CentOS: 7
#  Rocky: 8.4
#  OracleLinux: 7
#  Ubuntu: 18.04
#  Debian: 10
#  AlmaLinux: 8.3

postgressql_src_url: https://ftp.postgresql.org/pub/source/v14.6/postgresql-14.6.tar.gz
postgressql_src_ver: postgresql-14.6
src_dir: /usr/local/src
pg_home: /usr/pgsql-14/


# postgressql_src_url: https://ftp.postgresql.org/pub/source/v13.9/postgresql-13.9.tar.gz
# postgressql_src_ver: postgresql-13.9
# src_dir: /usr/local/src
# pg_home: /usr/pgsql-13/
