---
# "Check system" variables

os_valid_distributions:
  - RedHat
  - CentOS
  - Rocky
#  - OracleLinux
#  - Ubuntu
#  - Debian
#  - AlmaLinux

os_minimum_versions:
  RedHat: 8
  CentOS: 8
  Rocky: 8
#  OracleLinux: 7
#  Ubuntu: 18.04
#  Debian: 10
#  AlmaLinux: 8.3

# PostgreSQL 15 settings
postgresql_src_url: https://ftp.postgresql.org/pub/source/v15.3/postgresql-15.3.tar.gz
postgresql_src_ver: postgresql-15.3
src_dir: /usr/local/src
pg_home: /usr/pgsql-15/  # NDB standard path format
