- name: yum update
  yum:
    name: '*'
    state: latest

- name: add the /etc/yum.repos.d/epel.repo
  yum:
    name: epel-release
    state: present

- name: install python36, python3-devel
  yum:
    name:
      - python36
      - python3-devel
    state: latest

- name: pip3 install
  yum:
    name: ["python3-pip"]
    state: latest

- name: Install and upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip3

- name: Install dependency packages
  yum:
    name:
      - wget
      - zip
      - unzip
      - curl
      - net-tools
      - sshpass
      - gcc
      - rsync
      - iptables-services
      - lsof
      - readline-devel
      - zlib-devel
      - rpcbind
      - showmount
    state: latest
