---
# roles/postgres_ha/tasks/centos7.yml

- name: Set CentOS 7 specific HA variables
  ansible.builtin.set_fact:
    postgres_ha_python3_cmd: python3
    postgres_ha_pip_executable: python3
    postgres_ha_patroni_package: "patroni[etcd]==2.1.1"
    postgres_ha_haproxy_package: "haproxy*1.5*"
    postgres_ha_keepalived_package: keepalived
    postgres_ha_firewalld_package: firewalld
    postgres_ha_etcd_package: etcd-3.3.11

- name: Install CentOS 7 base packages
  ansible.builtin.package:
    name:
      - epel-release
      - python36
      - python3-devel
      - python3-pip
      - wget
      - zip
      - unzip
      - curl
      - net-tools
      - sshpass
      - gcc
      - rsync
      - iptables-services
      - lsof
      - readline-devel
      - zlib-devel
      - rpcbind
      - showmount
      - "{{ postgres_ha_haproxy_package }}"
      - "{{ postgres_ha_keepalived_package }}"
      - "{{ postgres_ha_firewalld_package }}"
      - "{{ postgres_ha_etcd_package }}"
    state: present
    update_cache: true

- name: Upgrade setuptools
  ansible.builtin.pip:
    name: setuptools
    executable: python3
    state: present
    extra_args: --upgrade

- name: Upgrade pip
  ansible.builtin.pip:
    name: pip
    executable: python3
    state: present
    extra_args: --upgrade

- name: Get Python3 pip version
  ansible.builtin.command:
    cmd: python3 -m pip --version
  register: postgres_ha_pip3_info
  changed_when: false

- name: Show Python3 pip version
  ansible.builtin.debug:
    var: postgres_ha_pip3_info.stdout_lines

- name: Start iptables service on CentOS 7
  ansible.builtin.service:
    name: iptables
    state: started
    enabled: true

- name: Include HA common tasks for CentOS 7
  ansible.builtin.include_tasks: ha_common.yml
