- name: add the /etc/yum.repos.d/epel.repo
  yum_repository:
    name: epel
    description: EPEL repo
    baseurl: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

- name: yum update
  yum:
    name: '*'
    state: latest
  async: 1000
  poll: 1
  register: yum_sleeper

- name: yum check on fire and forget task
  async_status:
    jid: "{{ yum_sleeper.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 30
  delay: 10

- name: install python36, python3-devel
  yum:
    name:
      - python36
      - python3-devel
    state: latest

- name: pip3 install
  yum:
    name: ["python3-pip"]
    state: latest

- name: Install and upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip3

- name: Install dependency packages
  yum:
    name:
      - wget
      - zip
      - unzip
      - curl
      - net-tools
      - sshpass
      - gcc
      - rsync
      - iptables-services
      - lsof
      - readline-devel
      - zlib-devel
      - rpcbind
      - showmount
    state: latest
