---
# roles/postgres_ha/tasks/main.yml

# OS common settings
- name: Create OS group postgres
  group:
    name: postgres
    state: present

- name: Create OS user postgres
  user:
    name: postgres
    password: "{{ postgres_user_password }}"
    home: /home/postgres
    group: postgres
    state: present

- name: Create OS group era
  group:
    name: era
    state: present

- name: Create OS user era
  user:
    name: era
    password: "{{ era_user_password }}"
    home: /home/era
    group: era
    state: present

- name: Enable passwordless sudo for era
  copy:
    content: "era ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/era_nopasswd
    mode: 0440

# rhel7/centos7 specific tasks
- include: centos7.yml
  when:
   - ansible_distribution in ["RedHat","CentOS"]
   - ansible_distribution_major_version == "7"

# rhel8 soecific tasks
- include: rhel8.yml
  when:
   - ansible_distribution == "RedHat"
   - ansible_distribution_major_version == "8"

# Install postgresql from source
- name: download postgresql packages
  get_url:
    url: "{{ postgressql_src_url }}"
    dest: "{{ src_dir }}"

- name: extract postgresql src
  command: chdir={{ src_dir }} tar xzvf "{{ postgressql_src_ver }}.tar.gz"

- name: configure postgresql
  command: chdir={{src_dir}}/{{postgressql_src_ver}} ./configure --prefix={{ pg_home }}

- name: make postgresql
  command: chdir={{src_dir}}/{{postgressql_src_ver}} make

- name: make all postgresql
  command: chdir={{src_dir}}/{{postgressql_src_ver}} make all

- name: make world postgresql
  command: chdir={{src_dir}}/{{postgressql_src_ver}} make world

- name: make install postgresql
  command: chdir={{src_dir}}/{{postgressql_src_ver}} make install

- name: make install-world postgresql
  command: chdir={{src_dir}}/{{postgressql_src_ver}} make install-world

- name: disable IPv6
  copy:
    content: |
      "net.ipv6.conf.all.disable_ipv6=1"
      "net.ipv6.conf.default.disable_ipv6=1"
    dest:  /etc/sysctl.d/disable_ipv6.conf
    mode: 0640

- name: Disabling seLinux state
  command: 'sed -i -e "s/^SELINUX=.*/SELINUX=disabled/g" /etc/sysconfig/selinux'

- name: Print the changes in seLinux Configurtion file 
  command: grep SELINUX /etc/sysconfig/selinux
  register: sevalue
- debug: msg="{{ sevalue.stdout_lines }}"
