---
# roles/postgres_ha/tasks/main.yml

# OS common settings
- name: Create OS group postgres
  ansible.builtin.group:
    name: postgres
    state: present

- name: Create OS user postgres
  ansible.builtin.user:
    name: postgres
    password: "{{ postgres_user_password }}"
    home: /home/postgres
    group: postgres
    state: present

- name: Create OS group era
  ansible.builtin.group:
    name: era
    state: present

- name: Create OS user era
  ansible.builtin.user:
    name: era
    password: "{{ era_user_password }}"
    home: /home/era
    group: era
    state: present

- name: Enable passwordless sudo for era
  ansible.builtin.copy:
    content: "era ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/era_nopasswd
    mode: '0440'
    validate: 'visudo -cf %s'

- name: Include CentOS7 specific tasks
  ansible.builtin.include_tasks: centos7.yml
  when:
    - ansible_distribution in ["RedHat","CentOS"]
    - ansible_distribution_major_version == "7"

- name: Include RHEL8 specific tasks
  ansible.builtin.include_tasks: rhel8.yml
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "8"

# Install postgresql from source
- name: Download PostgreSQL packages
  ansible.builtin.get_url:
    url: "{{ postgresql_src_url }}"
    dest: "{{ src_dir }}/{{ postgresql_src_ver }}.tar.gz"
    mode: '0644'

- name: Extract PostgreSQL source
  ansible.builtin.unarchive:
    src: "{{ src_dir }}/{{ postgresql_src_ver }}.tar.gz"
    dest: "{{ src_dir }}"
    remote_src: true
    owner: postgres
    group: postgres

- name: Configure PostgreSQL
  ansible.builtin.command:
    cmd: ./configure --prefix={{ pg_home }}
    chdir: "{{ src_dir }}/{{ postgresql_src_ver }}"
  args:
    creates: "{{ src_dir }}/{{ postgresql_src_ver }}/config.status"

- name: Build PostgreSQL
  ansible.builtin.command:
    cmd: make
    chdir: "{{ src_dir }}/{{ postgresql_src_ver }}"
  args:
    creates: "{{ src_dir }}/{{ postgresql_src_ver }}/src/backend/postgres"

- name: Build all PostgreSQL targets
  ansible.builtin.command:
    cmd: make all
    chdir: "{{ src_dir }}/{{ postgresql_src_ver }}"
  args:
    creates: "{{ src_dir }}/{{ postgresql_src_ver }}/src/backend/postgres"

- name: Build PostgreSQL world
  ansible.builtin.command:
    cmd: make world
    chdir: "{{ src_dir }}/{{ postgresql_src_ver }}"
  args:
    creates: "{{ src_dir }}/{{ postgresql_src_ver }}/src/backend/postgres"

- name: Install PostgreSQL
  ansible.builtin.command:
    cmd: make install
    chdir: "{{ src_dir }}/{{ postgresql_src_ver }}"
  args:
    creates: "{{ pg_home }}/bin/postgres"

- name: Install PostgreSQL world
  ansible.builtin.command:
    cmd: make install-world
    chdir: "{{ src_dir }}/{{ postgresql_src_ver }}"
  args:
    creates: "{{ pg_home }}/bin/postgres"

- name: Disable IPv6
  ansible.builtin.copy:
    content: |
      net.ipv6.conf.all.disable_ipv6=1
      net.ipv6.conf.default.disable_ipv6=1
    dest: /etc/sysctl.d/disable_ipv6.conf
    mode: '0640'

- name: Disable SELinux in config
  ansible.builtin.replace:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    replace: 'SELINUX=disabled'

- name: Print the changes in SELinux configuration file
  ansible.builtin.command:
    cmd: grep SELINUX /etc/selinux/config
  register: postgres_ha_sevalue
  changed_when: false

- name: Debug SELinux config output
  ansible.builtin.debug:
    var: postgres_ha_sevalue.stdout_lines
